### ISSUE TITLE
Get the index level that is currently active in the building for indoor maps

### ISSUE THREAD

**Issue by mmartinalo** [xantiagoma/google_maps_controller#2]
## Dependencies & doctor
google_maps_controller: ^1.1.0

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 4.0)
```

## Context
I am developing a new feature in my application to show information inside the buildings. When I initialize the map I do it with both _indoorViewEnabled_ and  _buildingsEnabled_ flags set to true 

More info
https://www.google.com/maps/about/partners/indoormaps/
https://developers.google.com/android/reference/com/google/android/gms/maps/model/IndoorBuilding

## Issue

Currently I am not be able to recover neither the level the map is at nor that the user selects. Is there a way to get this information?

Thank you in advance.

**Comment by xantiagoma** [comment]
Hi @mmartinalo  currently I don't see anything related to indoor maps in the main package, probably is something not develop yet. the google_maps_flutter is a wrapper on top of the iOS / Android official libraries so probably you'll need to write some native code/channels or so to achieve this.

I'm sorry I couldn't be more helpful.
