### ISSUE TITLE
How to drag move markers?

### ISSUE THREAD

**Issue by shujaatak** [xantiagoma/google_maps_controller#4]
It would be highly productive if one could drag move markers. If there is an option already then an example would be appreciated.

**Comment by xantiagoma** [comment]
https://stackoverflow.com/questions/55003179/flutter-drag-marker-and-get-new-position

That's something managed by google_maps_flutter library in the Marker class https://pub.dev/documentation/google_maps_flutter_platform_interface/latest/google_maps_flutter_platform_interface/Marker-class.html

```dart
Marker(
          onTap: () {
            print('Tapped');
          },
          draggable: true,
          markerId: MarkerId('Marker'),
          position: LatLng(value.latitude, value.longitude),
          onDragEnd: ((newPosition) {
            print(newPosition.latitude);
            print(newPosition.longitude);
          }))
```
